import reflex as rx
from rxconfig import config
from my_app_name.template.template import base_page
from my_app_name.ui.social_link import social_link
@rx.page(route="/about")
def about() -> rx.Component:
    return base_page(
        rx.container(
            rx.flex(
                rx.flex(
                    rx.flex(
                        rx.box(
                            width="100%",
                            height="20%",
                        ),
                        rx.hstack(
                            rx.avatar(
                                src="/image.png",
                                border_radius="100px 100px",
                                border="5px solid #ffffff",
                                height="80%",
                                width="auto",
                                ),
                            rx.heading(
                                "SKyoKen", 
                                weight="bold",
                                font_family="MyFont",
                                font_size="4em",
                                color="#ffffff",
                            ),
                            width="100%",
                            height="30%",
                            align_items="center",
                        ),
                        rx.vstack(
                            rx.text(
                                "Major in information System Engineering.",
                            ),
                            font_size="1.25em",
                            align_items="center",
                            justify="center",
                            color="#ffffff",
                            width="100%",
                            height="30%",
                        ),
                        rx.center(
                            social_link(
                                "instagram", 
                                "/#",
                                color="#ffffff",
                                size=25
                            ),
                            social_link(
                                "twitter", 
                                "/#",
                                color="#ffffff",
                                size=25
                            ),
                            social_link(
                                "facebook", 
                                "/#",
                                color="#ffffff",
                                size=25
                            ),
                            social_link(
                                "linkedin", 
                                "/#",
                                color="#ffffff",
                                size=25
                            ),
                            social_link(
                                "github", 
                                "/#",
                                color="#ffffff",
                                size=25
                            ),
                            spacing="2",
                            width="100%",
                            height="10%",
                        ),
                        rx.box(
                            width="100%",
                            height="10%",
                        ),
                        spacing="1",
                        padding="1em",
                        flex_direction="column",
                        height="100%",
                        width="100%",
                    ),
                    rx.flex(
                        rx.box(
                            width="100%",
                            height="14%",
                        ),
                        rx.flex(
                            rx.icon("hand-metal",size=35),
                            rx.text(
                                "", 
                                font_size="2em",
                                weight="bold"
                            ),
                            color="#ffffff",
                            spacing="2",
                            flex_direction="row",
                            width="100%",
                            height="8%",
                        ),
                        rx.flex(
                            rx.box(
                                rx.button(
                                    bg=rx.color("accent", 3),
                                    width="100%",
                                    height="100%",
                                ),
                                width="50%",
                                height="100%",
                            ),
                            rx.box(
                                rx.button(
                                    bg=rx.color("accent", 3),
                                    width="100%",
                                    height="100%",
                                ),
                                width="50%",
                                height="100%",
                            ),
                            height="40%",
                            width="100%",
                            spacing="4",
                            flex_direction="row",
                        ),
                        rx.flex(
                            rx.icon("paw-print",size=35),
                            rx.text(
                                "Pet", 
                                font_size="2em",
                                weight="bold"
                            ),
                            color="#ffffff",
                            spacing="2",
                            flex_direction="row",
                            width="100%",
                            height="8%",
                        ),
                        rx.flex(
                            rx.card(
                                rx.avatar(
                                    src="/image.png",
                                    border_radius="50px 50px",
                                    border="2px solid #ffffff",
                                    height="40%",
                                    width="auto",
                                ),
                                height="100%",
                                width="50%",
                            ),
                            rx.flex(
                                rx.card(
                                    rx.avatar(
                                        src="/image.png",
                                        border_radius="50px 50px",
                                        border="2px solid #ffffff",
                                        height="100%",
                                        width="auto",
                                    ),
                                    width="100%",   
                                    height="50%",
                                ),
                                rx.card(
                                    rx.avatar(
                                        src="/image.png",
                                        border_radius="50px 50px",
                                        border="2px solid #ffffff",
                                        height="100%",
                                        width="auto",
                                    ),
                                    width="100%",   
                                    height="50%",
                                ),
                                height="100%",
                                width="50%",
                                spacing="4",
                                flex_direction="column",
                            ),
                            height="30%",
                            width="100%",
                            spacing="4",
                            flex_direction="row",
                        ),
                        spacing="4",
                        padding="1em",
                        flex_direction="column",
                        height="100%",
                        width="100%",
                    ),
                    width="100%",
                    height="100%",
                    spacing="4",
                    flex_direction="row",
                ),
                bg=rx.color("accent", 10),
                font_family="MyFont",
                spacing="4",
                padding="1em",
                flex_direction="column",
                height="600px",
                width="100%",
                ),
            ),
        )